### PR TITLE
Release 1.5

### LINKED ISSUE #32: Switch to python3
`2to3 -w filename.py` can be used to autoconvert the script. However this gives a few errors, as not all is translated correct.

Edit: it took some time but I think i managed to get the code working. I have not tested all options yet though. Please test release 1.5

### PR DESCRIPTION
**Pull request by NicoHood**
**Do  not merge yet, this needs further testing.**
Readme also needs to be updated.

fixes #32

### CODE REVIEW

**Comment by NicoHood** [comment]
It looks like ikelos also updated a few parts of his script:
https://github.com/ikelos/shuffle-db-ng

However he is not watching his own repository, so he will never recognize my PR probably. He is also probably not aware of our great fork now. Too bad :(

**Comment by NicoHood** [comment]
I've resolved the conflicts. Please still do not merge yet.

I've also browsed through the github forks and found some projects with a few changes. Those include some text2speak improvements, also for mac for example or windows compatiblity (even if i personally do not care). We should have a look at this and see what we can use.
* https://github.com/thomas-hori/IPod-Shuffle-4g
* https://github.com/jdloft/IPod-Shuffle-4g
* https://github.com/jdloft/IPod-Shuffle-4g
* https://github.com/busywiththingsalreadyforgotten/IPod-Shuffle-4g
* https://github.com/antongulenko/IPod-Shuffle-4g

**Comment by skosch** [comment]
What's the status of this PR? I just hacked together my own Python3-compatible version before I discovered you guys had already done the work but just not merged it yet :roll_eyes: maybe it would be a good idea to release this for now, and deal with fancier TTS later?

**Comment by NicoHood** [comment]
Give it a review and suggest changes if you have any.

**Comment by skosch** [comment]
Definitely looks cleaner than my ad-hoc hackery, and works fine for me when I tested it a minute ago :+1: 
Just out of curiosity, why did you reverse the 4-byte strings (e.g. `("header_id", ("4s", b"hphs")), #shph`)?

**Comment by NicoHood** [comment]
I have no idea, i guess the byte oder in different encoded/decoded with this special bytestring and thatswhy i needed to change them. Its been years ago, so I dont remember anything at all. But I did the changes as careful as I could.

**Comment by skosch** [comment]
Alright then! Just asking because I hadn't reversed anything, and I still had music coming out of my iPod. But since it seems to be working, I would say go ahead and merge?

**Comment by NicoHood** [comment]
@nims11 I would also merge it and have a look at the mentioned PRs at a later time. Python2 is getting depreciated soon, we should just get rid of it. The shuffle is EOL anyways, so I dont think that much development is needed, we've fixed most of the things.

**Comment by nims11** [comment]
About time to wrap this up. I will pull out my shuffle from the dust and start helping out. Starting by reviewing this PR.

**Comment by NicoHood** [comment]
@nims11 can we merge this request now?

**Comment by thepalbi** [comment]
Also think we could merge this. Looked at the PR and seems OK to me. Will start looking into improving T2S and using it, latest version of iTunes doesn't support the my holy shuffle 😅

**Comment by nims11** [comment]
Just one small fix needed.

```python
diff --git a/ipod-shuffle-4g.py b/ipod-shuffle-4g.py
index 62e6052..1a2e349 100755
--- a/ipod-shuffle-4g.py
+++ b/ipod-shuffle-4g.py
@@ -32,14 +32,14 @@ def make_dir_if_absent(path):
 
 def raises_unicode_error(str):
     try:
-        str.decode('utf-8').encode('latin-1')
+        str.encode('latin-1')
         return False
     except (UnicodeEncodeError, UnicodeDecodeError):
         return True
 
 def hash_error_unicode(item):
-    return "".join(["{0:02X}".format(ord(x)) for x in reversed(hashlib.md5(item).digest()[:8])])
-    pass
+    item_bytes = item.encode('utf-8')
+    return "".join(["{0:02X}".format(ord(x)) for x in reversed(hashlib.md5(item_bytes).hexdigest()[:8])])
 
 def validate_unicode(path):
     path_list = path.split('/')
```

Context: In order to make paths with non latin characters work, there is a `-u` option in the script which renames such paths to their md5 hexdigest, which rely on the above two methods. Even if shuffle does support non latin filenames, the encoding doesn't seem to be utf-8 or utf-16. Hence the above hack.

Other than that, everything seems to be working and the PR looks good to me!

**Comment by nims11** [comment]
Minor changes

1. Update the version in the `--help` output
2. Update the changelog in readme.

**Comment by NicoHood** [comment]
@nims11 I've applied your suggestions, I think we are ready for a next release. If you wish, please merge the PR.

I suggest that you as lead maintainer also signs the new release via GPG similar to the previous release. If you need help with that, checkout [gpgit](https://github.com/NicoHood/gpgit), ask me, or I can also take over that part, if you wish. I recommend to create your own tarball (instead of downloading the github one) as it is the only safe way and the tarball will not change with newer github/git releases.

**Pull request merged**
