### PR TITLE
Plssync

### PR DESCRIPTION
**Pull request by sschuhmann**
This converts the track paths from bytestring to strings. This way this fixes the current workflow of creating pls playlists

### CODE REVIEW

**Comment by NicoHood** [comment]
Could you please go more into detail what this fixes? I guess a .pls playlist with öäü for example?

**Comment by sschuhmann** [comment]
I haven't been able to synchronize my iPod with this script and Python 3. This PR fixes the string conversion which might have been the problem between Python 2 and Python 3.

However, this might not be needed since your port to Python 3. I'll give it a try soon.

**Comment by NicoHood** [comment]
Yeah, please give it another try :-)

**Comment by sschuhmann** [comment]
I don't have any problems with Python3 and the current version of the script. This PR is then obsolete

**Comment by NicoHood** [comment]
Did you also run into this problem?
https://github.com/nims11/IPod-Shuffle-4g/pull/50

**Pull request closed without merging**
