### PR TITLE
Add #41 to Tips and Tricks Readme section

### LINKED ISSUE #41: How to format/restore iPod Shuffle 4G?
First off, thank you for sharing this absolutely fantastic little script, and I hope I can be forgiven for asking for help here, although this isn't strictly a bug:

This morning, my iPod was "full" – really, the hidden Trash folder was, but I didn't know of its existence at the time. Annoyed and a bit cavalierly, I reformatted the device (as GPT with a single FAT partition). Now I can add files again and run your script without problems. However, when I switch the thing on the LED lights up red and the voice says "Please use iTunes to restore this iPod."

I am hoping that someone might be able to share their partition configuration with me, and chime in with any ideas about what exactly the iPod firmware may be looking for? :bowing_man:

### PR DESCRIPTION
**Pull request by NicoHood**
Tested with @skosch . Thanks!

fix #41

### CODE REVIEW

**Comment by nims11** [comment]
Nice, I always thought the itunes restoration did something fancy, turns out I was wrong. Ready to merge?

PS: so the default voiceover files aren't required correct?

**Comment by skosch** [comment]
Yeah that's all I needed. Turned it off and on again and the files were back

**Comment by NicoHood** [comment]
I also did not expect that. I have not tested it though, the information relies on @skosch. But even if not, the ipod at least works. And if somebody still requires the original files: I backed them up.

**Comment by nims11** [comment]
It works, tested after destroying the partition table.

**Pull request merged**
