### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NicoHood**
Please keep this PR open.

I am creating an AUR package for arch which should also be added to the readme. This will take a few more days.

### CODE REVIEW

**Comment by NicoHood** [comment]
Ready to merge. Feel free to test the PKGBUILD.

**Comment by nims11** [comment]
We should specify python2. python3 is becoming/will become the default python in distros (I also use default python3).

**Comment by NicoHood** [comment]
Can't we update the script to python3 then?

**Comment by nims11** [comment]
Yea we can. Infact there is a handy tool `2to3` (comes with default python) which can make the task easier. Will have to review it though since py3 has some unicode changes which might affect us.

**Pull request merged**
